@URL = http://localhost:3000

### create patients
POST {{ URL }}/patients HTTP/1.1
Content-Type: application/json

{
  "name": "Gustavo H.",
  "email": "gugah@hotmail.com",
  "phone": "(11) 99999-9999"
}


### create doctors
POST {{ URL }}/doctors HTTP/1.1
Content-Type: application/json

{
  "name": "Dra. Andressa Cavalcante",
  "specialty": "Pediatra",
  "price": 100
}

### create doctor's schedule
POST {{ URL }}/doctors/5b29f9a7-d372-41fd-9741-3fa2fb24892c/schedule HTTP/1.1
Content-Type: application/json

{
  "availableFromWeekDay": 3,
  "availableToWeekDay": 3,
  "availableFromTime": "08:00",
  "availableToTime": "12:00"
}

### create appointments
POST {{ URL }}/appointments HTTP/1.1
Content-Type: application/json

{
  "patientId": "a471f09f-d812-4061-a289-9b4ddfd5bc80",
  "doctorId": "5b29f9a7-d372-41fd-9741-3fa2fb24892c",
  "createdAt": "2025-12-09T10:00:00.000Z"
}